import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | MindCast',
  description: 'Terms of Service for MindCast - AI-powered audio learning platform',
};

export default function TermsPage() {
  return (
    <div className="prose prose-gray mx-auto max-w-3xl dark:prose-invert">
      <h1>Terms of Service</h1>
      <p className="text-text-muted">Last updated: February 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using MindCast ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        MindCast is an AI-powered platform that generates educational audio content on topics of your choosing. The Service uses artificial intelligence to research, write, and narrate documentary-style audio episodes.
      </p>

      <h2>3. User Accounts</h2>
      <p>
        To use certain features of the Service, you must create an account using Google Sign-In. You are responsible for:
      </p>
      <ul>
        <li>Maintaining the confidentiality of your account</li>
        <li>All activities that occur under your account</li>
        <li>Notifying us immediately of any unauthorized use</li>
      </ul>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Generate content that is illegal, harmful, or violates the rights of others</li>
        <li>Attempt to circumvent usage limits or rate limiting</li>
        <li>Reverse engineer or attempt to extract the AI models or algorithms</li>
        <li>Use the Service for any commercial purpose without authorization</li>
        <li>Generate content that promotes violence, hate speech, or discrimination</li>
        <li>Create content that infringes on intellectual property rights</li>
      </ul>

      <h2>5. AI-Generated Content</h2>
      <p>
        You acknowledge that content generated by MindCast is created by artificial intelligence and may:
      </p>
      <ul>
        <li>Contain inaccuracies or errors</li>
        <li>Not reflect the most current information</li>
        <li>Require independent verification for important decisions</li>
      </ul>
      <p>
        MindCast makes no warranties about the accuracy, completeness, or reliability of AI-generated content. You are responsible for verifying any information before relying on it.
      </p>

      <h2>6. Intellectual Property</h2>
      <p>
        <strong>Your Content:</strong> You retain ownership of the topics and prompts you provide. You grant MindCast a license to process this content to provide the Service.
      </p>
      <p>
        <strong>Generated Content:</strong> Subject to your subscription terms, you receive a license to use audio episodes generated for your personal, non-commercial use. Pro subscribers may use content for commercial purposes as outlined in their subscription agreement.
      </p>
      <p>
        <strong>Our Service:</strong> MindCast and its underlying technology, including AI models, algorithms, and user interface, are owned by us and protected by intellectual property laws.
      </p>

      <h2>7. Subscription and Payments</h2>
      <p>
        <strong>Free Tier:</strong> Includes limited episode generation. Usage limits may change at any time.
      </p>
      <p>
        <strong>Pro Subscription:</strong> Billed monthly or annually. Subscriptions auto-renew unless cancelled. Refunds are provided as required by law.
      </p>
      <p>
        We reserve the right to change pricing with 30 days notice to existing subscribers.
      </p>

      <h2>8. Termination</h2>
      <p>
        We may suspend or terminate your access to the Service at any time for violations of these terms or for any other reason at our discretion. You may cancel your account at any time through your account settings.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, MINDCAST SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
      </p>

      <h2>11. Changes to Terms</h2>
      <p>
        We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms. We will notify users of material changes via email or in-app notification.
      </p>

      <h2>12. Contact</h2>
      <p>
        For questions about these terms, please contact us at:{' '}
        <a href="mailto:legal@mindcast.app" className="text-brand hover:underline">
          legal@mindcast.app
        </a>
      </p>
    </div>
  );
}
